// ─── Supported language codes ─────────────────────────────────────────────────
export type LangCode = 'en' | 'fr' | 'nl' | 'de' | 'es' | 'ja' | 'ko' | 'ru' | 'el' | 'pt'

export const LANGUAGES: { code: LangCode; label: string; flag: string; short: string }[] = [
  { code: 'en', label: 'English',    flag: '🇬🇧', short: 'En' },
  { code: 'fr', label: 'Français',   flag: '🇫🇷', short: 'Fr' },
  { code: 'nl', label: 'Nederlands', flag: '🇳🇱', short: 'Nl' },
  { code: 'de', label: 'Deutsch',    flag: '🇩🇪', short: 'De' },
  { code: 'es', label: 'Español',    flag: '🇪🇸', short: 'Es' },
  { code: 'ja', label: '日本語',      flag: '🇯🇵', short: 'Ja' },
  { code: 'ko', label: '한국어',      flag: '🇰🇷', short: 'Ko' },
  { code: 'ru', label: 'Русский',    flag: '🇷🇺', short: 'Ru' },
  { code: 'el', label: 'Ελληνικά',   flag: '🇬🇷', short: 'El' },
  { code: 'pt', label: 'Português',  flag: '🇵🇹', short: 'Pt' },
]

// ─── Translation shape ─────────────────────────────────────────────────────────
export type Translations = {
  nav: {
    home: string; about: string; getApp: string
    searchPlaceholder: string; popularLabel: string
    popularSearches: string[]; searchingFor: string
  }
  hero: { heading1: string; heading2: string; tagline: string; description: string; cta: string }
  experience: {
    heading: string; description: string
    cardArtTag: string; cardArtTitle: string; cardArtVenue: string; cardArtTime: string
    cardMusicTag: string; cardMusicTitle: string; cardMusicVenue: string; cardMusicTime: string
    liveNow: string
  }
  category: { heading: string; subheading: string; music: string; food: string; night: string; cinema: string }
  iphone: {
    liveBadge: string; heading1: string; heading2: string; description: string
    stat1Label: string; stat2Label: string; stat3Label: string; cta: string
  }
  noProfiles: { line1: string; line2: string; line3: string; tagline: string }
  theExperience: { title: string; subtitle: string }
  legal: { privacyTitle: string; eulaTab: string; privacyTab: string; lastUpdated: string; legalLabel: string; questionsTitle: string; contactUs: string; jumpTo: string; termsTitle: string; termsIntro: string }
  places: {
    heading: string; memory: string
    echo1: string; echo2: string; echo3: string; closing: string
  }
  footer: { home: string; about: string; downloadApp: string; rights: string; privacy: string; terms: string }
  about: {
    whoWeAre: string; heading: string; subheading: string; ourMission: string
    missionHeading1: string; missionHeading2: string; missionDesc: string; missionQuote: string
    noPerformanceTitle: string; noPerformanceDesc: string
    noAttentionTitle: string; noAttentionDesc: string
    noContentTitle: string; noContentDesc: string
    philosophy: string; ourBelief: string
    beliefQuote1: string; beliefLine1: string; beliefLine2: string; beliefTagline: string
    values: string; whatWeStandFor: string
    card1Title: string; card1Lines: string[]
    card2Title: string; card2Lines: string[]
    card3Title: string; card3Lines: string[]
    ctaLine1a: string; ctaLine1b: string
    ctaLine2a: string; ctaLine2b: string
    ctaLine3a: string; ctaLine3b: string
    getApp: string
  }
}

// ─── All translations ──────────────────────────────────────────────────────────
export const translations: Record<LangCode, Translations> = {
  en: {
    nav: { home:'Home', about:'About', getApp:'Get App', searchPlaceholder:'Search events, artists, places…', popularLabel:'Popular', popularSearches:['Live Music','Art Exhibitions','Fashion Shows','Cultural Events'], searchingFor:'Searching for' },
    hero: { heading1:'Different Vibes.', heading2:'Different Places', tagline:'Just PRESENZ.', description:'Discover art, music, fashion, culture happening live near you.', cta:'Leave a Presenz' },
    experience: { heading:'A new way to experience culture.', description:"Presenz brings together live art, music, fashion, cinema, and city energy into one living map visible only while it's happening.", cardArtTag:'ART', cardArtTitle:'Contemporary Exhibition', cardArtVenue:'Fondation Beyeler', cardArtTime:'Now – 6:00 PM', cardMusicTag:'MUSIC', cardMusicTitle:'Jazz Night Sessions', cardMusicVenue:'Blue Note Club', cardMusicTime:'8:00 PM – Late', liveNow:'LIVE NOW' },
    category: { heading:'Explore by category', subheading:"Discover what's happening now across the city", music:'Music', food:'Food', night:'Night', cinema:'Cinema' },
    iphone: { liveBadge:'Live Now', heading1:"See what's happening.", heading2:"Where it's happening.", description:'Every pulse appears live on the map, exactly where the moment exists — and disappears automatically after 48 hours.', stat1Label:'Live Events', stat2Label:'Cities', stat3Label:'Event Window', cta:'Open Live Pulse' },
    theExperience: { title:'The Experience', subtitle:'From Discovery to Creation' },
    noProfiles: { line1:'No profiles.', line2:'No Followers.', line3:'No filters.', tagline:'Just Presenz.' },
    places: { heading:'Places are alive.', memory:'Places carry memory.', echo1:'Echoes of music.', echo2:'Traces of paint.', echo3:'Signs of people gathering, leaving, returning.', closing:'Presenz allows places to speak without being ranked, reviewed, or judged.' },
    legal: { privacyTitle:'Privacy & EULA', eulaTab:'EULA', privacyTab:'Privacy Policy', lastUpdated:'Last updated: February 2026', legalLabel:'Legal', questionsTitle:'Questions?', contactUs:'Contact Us', jumpTo:'Jump to:', termsTitle:'Terms & Conditions', termsIntro:'By accessing, installing, registering for, or using PRESENZ, you confirm that you have read, understood, and agree to be legally bound by these Terms.' },
    footer: { home:'Home', about:'About', downloadApp:'Download app', rights:'Presenz-IntusLab Inc. All rights reserved.', privacy:'Privacy Policy', terms:'Terms of Service' },
    about: { whoWeAre:'Who We Are', heading:'About', subheading:'A new kind of platform — built for presence, not performance.', ourMission:'Our Mission', missionHeading1:'Presenz is not', missionHeading2:'social media.', missionDesc:'Presenz is a system for noticing culture as it happens in places, moments, and atmospheres.', missionQuote:'"It exists to sense what is real, while it is still real."', noPerformanceTitle:'No performance', noPerformanceDesc:'It does not ask people to perform or curate their moments.', noAttentionTitle:'No attention reward', noAttentionDesc:'It does not reward attention, likes, or engagement loops.', noContentTitle:'No content machine', noContentDesc:'It does not turn your presence into shareable content.', philosophy:'Philosophy', ourBelief:'Our belief', beliefQuote1:"Culture doesn't need permission.", beliefLine1:'It happens in streets. In sound. In walls.', beliefLine2:'In moments that pass before anyone names them.', beliefTagline:'Culture is not content. It is PRESENZ.', values:'Values', whatWeStandFor:'What we stand for', card1Title:'No pressure', card1Lines:['No performance.','No followers.','No pressure.'], card2Title:'No feeds', card2Lines:['No feeds.','No rankings.','No validation loops.'], card3Title:'Nothing to win', card3Lines:['Nothing to win.','Nothing to compare.'], ctaLine1a:"You don't post.", ctaLine1b:'You notice.', ctaLine2a:"You don't scroll.", ctaLine2b:'You sense.', ctaLine3a:"You don't perform.", ctaLine3b:'You are present.', getApp:'Get App' },
  },

  fr: {
    nav: { home:'Accueil', about:'À propos', getApp:'Télécharger', searchPlaceholder:'Rechercher événements, artistes, lieux…', popularLabel:'Populaire', popularSearches:["Musique Live","Expositions d'Art","Défilés de Mode","Événements Culturels"], searchingFor:'Recherche en cours pour' },
    hero: { heading1:'Ambiances Différentes.', heading2:'Endroits Différents', tagline:'Juste PRESENZ.', description:"Découvrez l'art, la musique, la mode et la culture en direct près de chez vous.", cta:'Laisser une Presenz' },
    experience: { heading:'Une nouvelle façon de vivre la culture.', description:"Presenz rassemble l'art, la musique, la mode, le cinéma et l'énergie de la ville sur une carte vivante visible uniquement en temps réel.", cardArtTag:'ART', cardArtTitle:'Exposition Contemporaine', cardArtVenue:'Fondation Beyeler', cardArtTime:'Maintenant – 18h00', cardMusicTag:'MUSIQUE', cardMusicTitle:'Soirée Jazz Sessions', cardMusicVenue:'Blue Note Club', cardMusicTime:'20h00 – Tard', liveNow:'EN DIRECT' },
    category: { heading:'Explorer par catégorie', subheading:'Découvrez ce qui se passe maintenant dans la ville', music:'Musique', food:'Gastronomie', night:'Nuit', cinema:'Cinéma' },
    iphone: { liveBadge:'En Direct', heading1:'Voyez ce qui se passe.', heading2:'Là où ça se passe.', description:"Chaque impulsion apparaît en direct sur la carte, exactement là où le moment existe — et disparaît automatiquement après 48 heures.", stat1Label:'Événements Live', stat2Label:'Villes', stat3Label:'Fenêtre', cta:'Ouvrir Live Pulse' },
    theExperience: { title:"L'Expérience", subtitle:'De la Découverte à la Création' },
    noProfiles: { line1:'Pas de profils.', line2:"Pas d'abonnés.", line3:'Pas de filtres.', tagline:'Juste Presenz.' },
    places: { heading:'Les lieux sont vivants.', memory:'Les lieux portent la mémoire.', echo1:"Échos de musique.", echo2:'Traces de peinture.', echo3:'Signes de gens qui se rassemblent, partent, reviennent.', closing:"Presenz permet aux lieux de parler sans être classés, critiqués ou jugés." },
    legal: { privacyTitle:'Confidentialité & EULA', eulaTab:'EULA', privacyTab:'Politique de confidentialité', lastUpdated:'Dernière mise à jour: Février 2026', legalLabel:'Légal', questionsTitle:'Des questions?', contactUs:'Contactez-nous', jumpTo:'Aller à:', termsTitle:'Conditions Générales', termsIntro:"En accédant à PRESENZ, vous confirmez avoir lu et accepté ces conditions." },
    footer: { home:'Accueil', about:'À propos', downloadApp:"Télécharger l'app", rights:'Presenz-IntusLab Inc. Tous droits réservés.', privacy:'Politique de Confidentialité', terms:"Conditions d'Utilisation" },
    about: { whoWeAre:'Qui Nous Sommes', heading:'À propos', subheading:'Une nouvelle plateforme — faite pour la présence, pas la performance.', ourMission:'Notre Mission', missionHeading1:"Presenz n'est pas", missionHeading2:'des réseaux sociaux.', missionDesc:"Presenz est un système pour percevoir la culture telle qu'elle se produit dans les lieux, les moments et les atmosphères.", missionQuote:"\"Il existe pour sentir ce qui est réel, pendant que c'est encore réel.\"", noPerformanceTitle:'Pas de performance', noPerformanceDesc:'Il ne demande pas aux gens de performer ou de soigner leurs moments.', noAttentionTitle:"Pas de récompense d'attention", noAttentionDesc:"Il ne récompense pas l'attention, les likes ou les boucles d'engagement.", noContentTitle:'Pas de machine à contenu', noContentDesc:'Il ne transforme pas votre présence en contenu partageable.', philosophy:'Philosophie', ourBelief:'Notre croyance', beliefQuote1:"La culture n'a pas besoin de permission.", beliefLine1:'Elle se passe dans les rues. Dans le son. Dans les murs.', beliefLine2:'Dans des moments qui passent avant que quiconque les nomme.', beliefTagline:"La culture n'est pas du contenu. C'est PRESENZ.", values:'Valeurs', whatWeStandFor:'Ce pour quoi nous nous battons', card1Title:'Pas de pression', card1Lines:['Pas de performance.',"Pas d'abonnés.",'Pas de pression.'], card2Title:'Pas de fils', card2Lines:['Pas de flux.','Pas de classements.','Pas de boucles de validation.'], card3Title:'Rien à gagner', card3Lines:['Rien à gagner.','Rien à comparer.'], ctaLine1a:'Vous ne publiez pas.', ctaLine1b:'Vous remarquez.', ctaLine2a:'Vous ne faites pas défiler.', ctaLine2b:'Vous ressentez.', ctaLine3a:'Vous ne performez pas.', ctaLine3b:'Vous êtes présent.', getApp:'Télécharger' },
  },

  nl: {
    nav: { home:'Home', about:'Over ons', getApp:'App Downloaden', searchPlaceholder:'Zoek evenementen, artiesten, plaatsen…', popularLabel:'Populair', popularSearches:['Live Muziek','Kunsttentoonstellingen','Modeshows','Culturele Evenementen'], searchingFor:'Zoeken naar' },
    hero: { heading1:'Verschillende Vibes.', heading2:'Verschillende Plaatsen', tagline:'Gewoon PRESENZ.', description:'Ontdek kunst, muziek, mode en cultuur die live in de buurt plaatsvinden.', cta:'Laat een Presenz achter' },
    experience: { heading:'Een nieuwe manier om cultuur te beleven.', description:'Presenz brengt live kunst, muziek, mode, cinema en stadsenergie samen in één levende kaart die alleen zichtbaar is terwijl het gebeurt.', cardArtTag:'KUNST', cardArtTitle:'Hedendaagse Tentoonstelling', cardArtVenue:'Fondation Beyeler', cardArtTime:'Nu – 18:00', cardMusicTag:'MUZIEK', cardMusicTitle:'Jazz Avondsessies', cardMusicVenue:'Blue Note Club', cardMusicTime:'20:00 – Laat', liveNow:'LIVE NU' },
    category: { heading:'Verken per categorie', subheading:'Ontdek wat er nu in de stad gebeurt', music:'Muziek', food:'Eten', night:'Nacht', cinema:'Cinema' },
    iphone: { liveBadge:'Live Nu', heading1:'Zie wat er gebeurt.', heading2:'Waar het gebeurt.', description:'Elke puls verschijnt live op de kaart, precies waar het moment bestaat — en verdwijnt automatisch na 48 uur.', stat1Label:'Live Evenementen', stat2Label:'Steden', stat3Label:'Venster', cta:'Open Live Puls' },
    theExperience: { title:'De Ervaring', subtitle:'Van Ontdekking tot Creatie' },
    noProfiles: { line1:'Geen profielen.', line2:'Geen volgers.', line3:'Geen filters.', tagline:'Gewoon Presenz.' },
    places: { heading:'Plaatsen leven.', memory:'Plaatsen dragen herinneringen.', echo1:"Echo's van muziek.", echo2:'Sporen van verf.', echo3:'Tekenen van mensen die samenkomen, vertrekken, terugkeren.', closing:'Presenz laat plaatsen spreken zonder te worden gerangschikt, beoordeeld of veroordeeld.' },
    legal: { privacyTitle:'Privacy & EULA', eulaTab:'EULA', privacyTab:'Privacybeleid', lastUpdated:'Laatste update: februari 2026', legalLabel:'Juridisch', questionsTitle:'Vragen?', contactUs:'Neem contact op', jumpTo:'Spring naar:', termsTitle:'Algemene Voorwaarden', termsIntro:'Door PRESENZ te gebruiken, bevestigt u dat u deze voorwaarden hebt gelezen en accepteert.' },
    footer: { home:'Home', about:'Over ons', downloadApp:'App downloaden', rights:'Presenz-IntusLab Inc. Alle rechten voorbehouden.', privacy:'Privacybeleid', terms:'Servicevoorwaarden' },
    about: { whoWeAre:'Wie We Zijn', heading:'Over ons', subheading:'Een nieuw soort platform — gebouwd voor aanwezigheid, niet prestatie.', ourMission:'Onze Missie', missionHeading1:'Presenz is geen', missionHeading2:'sociale media.', missionDesc:'Presenz is een systeem om cultuur op te merken zoals het zich voordoet in plaatsen, momenten en sferen.', missionQuote:'"Het bestaat om te voelen wat echt is, terwijl het nog echt is."', noPerformanceTitle:'Geen prestatie', noPerformanceDesc:'Het vraagt mensen niet om hun momenten te performen of te cureren.', noAttentionTitle:'Geen aandachtsbeloning', noAttentionDesc:'Het beloont geen aandacht, likes of betrokkenheidslussen.', noContentTitle:'Geen contentmachine', noContentDesc:'Het verandert uw aanwezigheid niet in deelbare content.', philosophy:'Filosofie', ourBelief:'Onze overtuiging', beliefQuote1:'Cultuur heeft geen toestemming nodig.', beliefLine1:'Het gebeurt in straten. In geluid. In muren.', beliefLine2:'In momenten die voorbijgaan voordat iemand ze benoemt.', beliefTagline:'Cultuur is geen content. Het is PRESENZ.', values:'Waarden', whatWeStandFor:'Waar wij voor staan', card1Title:'Geen druk', card1Lines:['Geen prestatie.','Geen volgers.','Geen druk.'], card2Title:'Geen feeds', card2Lines:['Geen feeds.','Geen ranglijsten.','Geen validatielussen.'], card3Title:'Niets te winnen', card3Lines:['Niets te winnen.','Niets te vergelijken.'], ctaLine1a:'Je plaatst niet.', ctaLine1b:'Je merkt op.', ctaLine2a:'Je scrollt niet.', ctaLine2b:'Je voelt.', ctaLine3a:'Je presteert niet.', ctaLine3b:'Je bent aanwezig.', getApp:'App Downloaden' },
  },

  de: {
    nav: { home:'Startseite', about:'Über uns', getApp:'App holen', searchPlaceholder:'Events, Künstler, Orte suchen…', popularLabel:'Beliebt', popularSearches:['Live-Musik','Kunstausstellungen','Modeschauen','Kulturveranstaltungen'], searchingFor:'Suche nach' },
    hero: { heading1:'Andere Vibes.', heading2:'Andere Orte', tagline:'Nur PRESENZ.', description:'Entdecke Kunst, Musik, Mode und Kultur, die live in deiner Nähe stattfinden.', cta:'Eine Presenz hinterlassen' },
    experience: { heading:'Eine neue Art, Kultur zu erleben.', description:'Presenz vereint Live-Kunst, Musik, Mode, Kino und Stadtenergie in einer lebendigen Karte, die nur sichtbar ist, während es passiert.', cardArtTag:'KUNST', cardArtTitle:'Zeitgenössische Ausstellung', cardArtVenue:'Fondation Beyeler', cardArtTime:'Jetzt – 18:00 Uhr', cardMusicTag:'MUSIK', cardMusicTitle:'Jazz-Nacht-Sessions', cardMusicVenue:'Blue Note Club', cardMusicTime:'20:00 Uhr – Spät', liveNow:'JETZT LIVE' },
    category: { heading:'Nach Kategorie erkunden', subheading:'Entdecke, was jetzt in der Stadt passiert', music:'Musik', food:'Essen', night:'Nacht', cinema:'Kino' },
    iphone: { liveBadge:'Jetzt Live', heading1:'Sieh, was passiert.', heading2:'Wo es passiert.', description:'Jeder Puls erscheint live auf der Karte, genau dort, wo der Moment existiert — und verschwindet automatisch nach 48 Stunden.', stat1Label:'Live-Events', stat2Label:'Städte', stat3Label:'Zeitfenster', cta:'Live Pulse öffnen' },
    theExperience: { title:'Die Erfahrung', subtitle:'Von der Entdeckung zur Schöpfung' },
    noProfiles: { line1:'Keine Profile.', line2:'Keine Follower.', line3:'Keine Filter.', tagline:'Nur Presenz.' },
    places: { heading:'Orte leben.', memory:'Orte tragen Erinnerungen.', echo1:'Echos der Musik.', echo2:'Spuren von Farbe.', echo3:'Zeichen von Menschen, die sich versammeln, gehen und zurückkehren.', closing:'Presenz lässt Orte sprechen, ohne eingestuft, bewertet oder beurteilt zu werden.' },
    legal: { privacyTitle:'Datenschutz & EULA', eulaTab:'EULA', privacyTab:'Datenschutzrichtlinie', lastUpdated:'Zuletzt aktualisiert: Februar 2026', legalLabel:'Rechtliches', questionsTitle:'Fragen?', contactUs:'Kontakt', jumpTo:'Springen zu:', termsTitle:'Allgemeine Geschäftsbedingungen', termsIntro:'Durch die Nutzung von PRESENZ bestätigen Sie, diese Bedingungen gelesen und akzeptiert zu haben.' },
    footer: { home:'Startseite', about:'Über uns', downloadApp:'App herunterladen', rights:'Presenz-IntusLab Inc. Alle Rechte vorbehalten.', privacy:'Datenschutzrichtlinie', terms:'Nutzungsbedingungen' },
    about: { whoWeAre:'Wer Wir Sind', heading:'Über uns', subheading:'Eine neue Art von Plattform — gebaut für Präsenz, nicht für Leistung.', ourMission:'Unsere Mission', missionHeading1:'Presenz ist keine', missionHeading2:'sozialen Medien.', missionDesc:'Presenz ist ein System, um Kultur wahrzunehmen, wie sie in Orten, Momenten und Atmosphären geschieht.', missionQuote:'"Es existiert, um zu spüren, was real ist, solange es noch real ist."', noPerformanceTitle:'Keine Leistung', noPerformanceDesc:'Es verlangt nicht, dass Menschen ihre Momente performen oder kuratieren.', noAttentionTitle:'Keine Aufmerksamkeitsbelohnung', noAttentionDesc:'Es belohnt keine Aufmerksamkeit, Likes oder Engagement-Schleifen.', noContentTitle:'Keine Content-Maschine', noContentDesc:'Es verwandelt deine Präsenz nicht in teilbaren Inhalt.', philosophy:'Philosophie', ourBelief:'Unser Glaube', beliefQuote1:'Kultur braucht keine Erlaubnis.', beliefLine1:'Sie passiert in Straßen. In Klängen. In Wänden.', beliefLine2:'In Momenten, die vergehen, bevor sie jemand benennt.', beliefTagline:'Kultur ist kein Inhalt. Es ist PRESENZ.', values:'Werte', whatWeStandFor:'Wofür wir stehen', card1Title:'Kein Druck', card1Lines:['Keine Leistung.','Keine Follower.','Kein Druck.'], card2Title:'Keine Feeds', card2Lines:['Keine Feeds.','Keine Rankings.','Keine Validierungsschleifen.'], card3Title:'Nichts zu gewinnen', card3Lines:['Nichts zu gewinnen.','Nichts zu vergleichen.'], ctaLine1a:'Du postest nicht.', ctaLine1b:'Du bemerkst.', ctaLine2a:'Du scrollst nicht.', ctaLine2b:'Du spürst.', ctaLine3a:'Du performst nicht.', ctaLine3b:'Du bist präsent.', getApp:'App holen' },
  },

  es: {
    nav: { home:'Inicio', about:'Nosotros', getApp:'Obtener App', searchPlaceholder:'Buscar eventos, artistas, lugares…', popularLabel:'Popular', popularSearches:['Música en Vivo','Exposiciones de Arte','Desfiles de Moda','Eventos Culturales'], searchingFor:'Buscando' },
    hero: { heading1:'Diferentes Vibraciones.', heading2:'Diferentes Lugares', tagline:'Solo PRESENZ.', description:'Descubre arte, música, moda y cultura en vivo cerca de ti.', cta:'Dejar una Presenz' },
    experience: { heading:'Una nueva forma de vivir la cultura.', description:'Presenz reúne arte en vivo, música, moda, cine y energía urbana en un mapa vivo visible solo mientras sucede.', cardArtTag:'ARTE', cardArtTitle:'Exposición Contemporánea', cardArtVenue:'Fondation Beyeler', cardArtTime:'Ahora – 6:00 PM', cardMusicTag:'MÚSICA', cardMusicTitle:'Sesiones de Jazz Nocturno', cardMusicVenue:'Blue Note Club', cardMusicTime:'8:00 PM – Tarde', liveNow:'EN VIVO' },
    category: { heading:'Explorar por categoría', subheading:'Descubre lo que está pasando ahora en la ciudad', music:'Música', food:'Comida', night:'Noche', cinema:'Cine' },
    iphone: { liveBadge:'En Vivo Ahora', heading1:'Ve lo que está pasando.', heading2:'Donde está pasando.', description:'Cada pulso aparece en vivo en el mapa, exactamente donde existe el momento — y desaparece automáticamente después de 48 horas.', stat1Label:'Eventos en Vivo', stat2Label:'Ciudades', stat3Label:'Ventana', cta:'Abrir Live Pulse' },
    theExperience: { title:'La Experiencia', subtitle:'Del Descubrimiento a la Creación' },
    noProfiles: { line1:'Sin perfiles.', line2:'Sin seguidores.', line3:'Sin filtros.', tagline:'Solo Presenz.' },
    places: { heading:'Los lugares están vivos.', memory:'Los lugares llevan memoria.', echo1:'Ecos de música.', echo2:'Trazos de pintura.', echo3:'Señales de personas que se reúnen, parten y regresan.', closing:'Presenz permite que los lugares hablen sin ser clasificados, revisados o juzgados.' },
    legal: { privacyTitle:'Privacidad y EULA', eulaTab:'EULA', privacyTab:'Política de privacidad', lastUpdated:'Última actualización: Febrero 2026', legalLabel:'Legal', questionsTitle:'¿Preguntas?', contactUs:'Contáctenos', jumpTo:'Ir a:', termsTitle:'Términos y Condiciones', termsIntro:'Al acceder a PRESENZ, confirma haber leído y aceptado estos términos.' },
    footer: { home:'Inicio', about:'Nosotros', downloadApp:'Descargar app', rights:'Presenz-IntusLab Inc. Todos los derechos reservados.', privacy:'Política de Privacidad', terms:'Términos de Servicio' },
    about: { whoWeAre:'Quiénes Somos', heading:'Sobre Nosotros', subheading:'Una nueva clase de plataforma — construida para la presencia, no el rendimiento.', ourMission:'Nuestra Misión', missionHeading1:'Presenz no es', missionHeading2:'redes sociales.', missionDesc:'Presenz es un sistema para percibir la cultura tal como ocurre en lugares, momentos y atmósferas.', missionQuote:'"Existe para sentir lo que es real, mientras todavía es real."', noPerformanceTitle:'Sin rendimiento', noPerformanceDesc:'No pide a la gente que actúe ni cuide sus momentos.', noAttentionTitle:'Sin recompensa de atención', noAttentionDesc:'No recompensa la atención, los me gusta ni los bucles de participación.', noContentTitle:'Sin máquina de contenido', noContentDesc:'No convierte tu presencia en contenido compartible.', philosophy:'Filosofía', ourBelief:'Nuestra creencia', beliefQuote1:'La cultura no necesita permiso.', beliefLine1:'Sucede en calles. En sonidos. En paredes.', beliefLine2:'En momentos que pasan antes de que alguien los nombre.', beliefTagline:'La cultura no es contenido. Es PRESENZ.', values:'Valores', whatWeStandFor:'Lo que defendemos', card1Title:'Sin presión', card1Lines:['Sin actuación.','Sin seguidores.','Sin presión.'], card2Title:'Sin feeds', card2Lines:['Sin feeds.','Sin rankings.','Sin bucles de validación.'], card3Title:'Nada que ganar', card3Lines:['Nada que ganar.','Nada que comparar.'], ctaLine1a:'No publicas.', ctaLine1b:'Notas.', ctaLine2a:'No haces scroll.', ctaLine2b:'Sientes.', ctaLine3a:'No actúas.', ctaLine3b:'Estás presente.', getApp:'Obtener App' },
  },

  ja: {
    nav: { home:'ホーム', about:'について', getApp:'アプリを入手', searchPlaceholder:'イベント、アーティスト、場所を検索…', popularLabel:'人気', popularSearches:['ライブミュージック','アート展示','ファッションショー','文化イベント'], searchingFor:'検索中' },
    hero: { heading1:'様々なバイブス。', heading2:'様々な場所', tagline:'ただ PRESENZ。', description:'あなたの近くで今起きているアート、音楽、ファッション、文化を発見しよう。', cta:'Presenzを残す' },
    experience: { heading:'文化を体験する新しい方法。', description:'Presenzは、ライブアート、音楽、ファッション、映画、都市のエネルギーを、起きている間だけ見える一つの生きたマップに集約します。', cardArtTag:'アート', cardArtTitle:'現代アート展', cardArtVenue:'フォンダシオン・バイエラー', cardArtTime:'今 – 午後6時', cardMusicTag:'音楽', cardMusicTitle:'ジャズナイトセッション', cardMusicVenue:'ブルーノートクラブ', cardMusicTime:'午後8時 – 深夜まで', liveNow:'ライブ中' },
    category: { heading:'カテゴリで探す', subheading:'今、街で何が起きているか発見しよう', music:'音楽', food:'グルメ', night:'ナイト', cinema:'映画' },
    iphone: { liveBadge:'ライブ中', heading1:'何が起きているかを見よう。', heading2:'どこで起きているかも。', description:'すべてのパルスは、その瞬間が存在するまさにその場所にライブで地図上に表示され、48時間後に自動的に消えます。', stat1Label:'ライブイベント', stat2Label:'都市', stat3Label:'イベント期間', cta:'ライブパルスを開く' },
    theExperience: { title:'体験', subtitle:'発見から創造へ' },
    noProfiles: { line1:'プロフィールなし。', line2:'フォロワーなし。', line3:'フィルターなし。', tagline:'ただ Presenz。' },
    places: { heading:'場所は生きている。', memory:'場所は記憶を展る。', echo1:'音楽の旋律。', echo2:'ペンキの痕跡。', echo3:'人々が集まり、去り、戻ってくる気配。', closing:'Presenzは場所がランク付け、レビュー、判断されずに語ることを許します。' },
    legal: { privacyTitle:'プライバシーとEULA', eulaTab:'EULA', privacyTab:'プライバシーポリシー', lastUpdated:'最終更新: 2026年2月', legalLabel:'法的情報', questionsTitle:'ご質問?', contactUs:'お問い合わせ', jumpTo:'ジャンプ:', termsTitle:'利用規約', termsIntro:'PrESENZをご利用いただくことで、これらの規約を読み、同意したものとみなされます。' },
    footer: { home:'ホーム', about:'について', downloadApp:'アプリをダウンロード', rights:'Presenz-IntusLab Inc. 全著作権所有。', privacy:'プライバシーポリシー', terms:'利用規約' },
    about: { whoWeAre:'私たちについて', heading:'について', subheading:'新しい種類のプラットフォーム — パフォーマンスではなく、存在のために構築。', ourMission:'私たちのミッション', missionHeading1:'Presenzは', missionHeading2:'ソーシャルメディアではありません。', missionDesc:'Presenzは、場所、瞬間、雰囲気の中で起きている文化に気づくためのシステムです。', missionQuote:'「まだ現実のうちに、現実を感じるために存在します。」', noPerformanceTitle:'パフォーマンスなし', noPerformanceDesc:'人々に自分の瞬間をパフォーマンスやキュレーションすることを求めません。', noAttentionTitle:'注目報酬なし', noAttentionDesc:'注目、いいね、エンゲージメントループを報酬としません。', noContentTitle:'コンテンツマシンなし', noContentDesc:'あなたの存在をシェア可能なコンテンツに変換しません。', philosophy:'哲学', ourBelief:'私たちの信念', beliefQuote1:'文化は許可を必要としません。', beliefLine1:'それは通りで起きる。音の中で。壁の中で。', beliefLine2:'誰かが名付ける前に過ぎ去る瞬間の中で。', beliefTagline:'文化はコンテンツではありません。それが PRESENZ です。', values:'価値観', whatWeStandFor:'私たちが大切にすること', card1Title:'プレッシャーなし', card1Lines:['パフォーマンスなし。','フォロワーなし。','プレッシャーなし。'], card2Title:'フィードなし', card2Lines:['フィードなし。','ランキングなし。','承認ループなし。'], card3Title:'勝つものなし', card3Lines:['勝つものなし。','比べるものなし。'], ctaLine1a:'投稿しない。', ctaLine1b:'気づく。', ctaLine2a:'スクロールしない。', ctaLine2b:'感じる。', ctaLine3a:'パフォーマンスしない。', ctaLine3b:'存在する。', getApp:'アプリを入手' },
  },

  ko: {
    nav: { home:'홈', about:'소개', getApp:'앱 받기', searchPlaceholder:'이벤트, 아티스트, 장소 검색…', popularLabel:'인기', popularSearches:['라이브 음악','미술 전시','패션쇼','문화 행사'], searchingFor:'검색 중' },
    hero: { heading1:'다양한 바이브.', heading2:'다양한 장소', tagline:'그냥 PRESENZ.', description:'가까운 곳에서 라이브로 펼쳐지는 예술, 음악, 패션, 문화를 발견하세요.', cta:'Presenz 남기기' },
    experience: { heading:'문화를 경험하는 새로운 방법.', description:'Presenz는 라이브 예술, 음악, 패션, 영화, 도시 에너지를 하나의 살아있는 지도로 통합합니다.', cardArtTag:'예술', cardArtTitle:'현대 전시회', cardArtVenue:'폰다시옹 바이엘러', cardArtTime:'지금 – 오후 6시', cardMusicTag:'음악', cardMusicTitle:'재즈 나이트 세션', cardMusicVenue:'블루 노트 클럽', cardMusicTime:'오후 8시 – 늦게까지', liveNow:'라이브 중' },
    category: { heading:'카테고리별 탐색', subheading:'지금 도시에서 무슨 일이 일어나는지 발견하세요', music:'음악', food:'음식', night:'나이트', cinema:'영화' },
    iphone: { liveBadge:'라이브 중', heading1:'무슨 일이 일어나는지 보세요.', heading2:'어디서 일어나는지도.', description:'모든 펄스는 그 순간이 존재하는 정확한 위치에 라이브로 지도에 나타나며, 48시간 후 자동으로 사라집니다.', stat1Label:'라이브 이벤트', stat2Label:'도시', stat3Label:'이벤트 기간', cta:'라이브 펄스 열기' },
    theExperience: { title:'경험', subtitle:'발견에서 창조까지' },
    noProfiles: { line1:'프로필 없음.', line2:'팔로워 없음.', line3:'필터 없음.', tagline:'그냥 Presenz.' },
    places: { heading:'장소는 살아있다.', memory:'장소는 기억을 담는다.', echo1:'음악의 에코.', echo2:'페인트의 흔적.', echo3:'사람들이 모이고 떠나고 돌아오는 징표.', closing:'Presenz는 장소가 순위가 매겨지거나 평가되지 않고 말할 수 있게 합니다.' },
    legal: { privacyTitle:'개인정보 및 EULA', eulaTab:'EULA', privacyTab:'개인정보 처리방침', lastUpdated:'최종 업데이트: 2026년 2월', legalLabel:'법적 고지', questionsTitle:'문의?', contactUs:'문의하기', jumpTo:'이동:', termsTitle:'이용약관', termsIntro:'PRESENZ를 사용함으로써 이 약관을 읽고 동의한 것으로 간주됩니다.' },
    footer: { home:'홈', about:'소개', downloadApp:'앱 다운로드', rights:'Presenz-IntusLab Inc. 모든 권리 보유.', privacy:'개인정보 처리방침', terms:'서비스 약관' },
    about: { whoWeAre:'우리는 누구인가', heading:'소개', subheading:'새로운 종류의 플랫폼 — 성과가 아닌 존재를 위해 만들어졌습니다.', ourMission:'우리의 미션', missionHeading1:'Presenz는', missionHeading2:'소셜 미디어가 아닙니다.', missionDesc:'Presenz는 장소, 순간, 분위기 속에서 일어나는 문화를 인식하는 시스템입니다.', missionQuote:'"현실인 것을, 아직 현실인 동안 느끼기 위해 존재합니다."', noPerformanceTitle:'퍼포먼스 없음', noPerformanceDesc:'사람들에게 자신의 순간을 수행하거나 큐레이션하도록 요구하지 않습니다.', noAttentionTitle:'관심 보상 없음', noAttentionDesc:'관심, 좋아요, 참여 루프를 보상하지 않습니다.', noContentTitle:'콘텐츠 기계 없음', noContentDesc:'당신의 존재를 공유 가능한 콘텐츠로 전환하지 않습니다.', philosophy:'철학', ourBelief:'우리의 신념', beliefQuote1:'문화는 허락이 필요하지 않습니다.', beliefLine1:'거리에서. 소리에서. 벽에서 일어납니다.', beliefLine2:'누군가가 이름 붙이기 전에 지나가는 순간들 속에서.', beliefTagline:'문화는 콘텐츠가 아닙니다. 그것은 PRESENZ입니다.', values:'가치', whatWeStandFor:'우리가 지향하는 것', card1Title:'압박 없음', card1Lines:['퍼포먼스 없음.','팔로워 없음.','압박 없음.'], card2Title:'피드 없음', card2Lines:['피드 없음.','순위 없음.','검증 루프 없음.'], card3Title:'이길 것 없음', card3Lines:['이길 것 없음.','비교할 것 없음.'], ctaLine1a:'게시하지 않습니다.', ctaLine1b:'알아차립니다.', ctaLine2a:'스크롤하지 않습니다.', ctaLine2b:'느낍니다.', ctaLine3a:'퍼포먼스하지 않습니다.', ctaLine3b:'존재합니다.', getApp:'앱 받기' },
  },

  ru: {
    nav: { home:'Главная', about:'О нас', getApp:'Скачать', searchPlaceholder:'Поиск событий, артистов, мест…', popularLabel:'Популярное', popularSearches:['Живая Музыка','Выставки Искусства','Показы Мод','Культурные Мероприятия'], searchingFor:'Поиск' },
    hero: { heading1:'Разные Вайбы.', heading2:'Разные Места', tagline:'Просто PRESENZ.', description:'Откройте для себя искусство, музыку, моду и культуру, которые происходят вживую рядом с вами.', cta:'Оставить Presenz' },
    experience: { heading:'Новый способ переживать культуру.', description:'Presenz объединяет живое искусство, музыку, моду, кино и городскую энергию в одну живую карту, видимую только пока это происходит.', cardArtTag:'ИСКУССТВО', cardArtTitle:'Современная Выставка', cardArtVenue:'Fondation Beyeler', cardArtTime:'Сейчас – 18:00', cardMusicTag:'МУЗЫКА', cardMusicTitle:'Джазовые Ночные Сессии', cardMusicVenue:'Blue Note Club', cardMusicTime:'20:00 – Поздно', liveNow:'В ЭФИРЕ' },
    category: { heading:'Исследуй по категориям', subheading:'Узнай, что происходит сейчас в городе', music:'Музыка', food:'Еда', night:'Ночь', cinema:'Кино' },
    iphone: { liveBadge:'В Эфире', heading1:'Смотри что происходит.', heading2:'Где это происходит.', description:'Каждый импульс появляется в прямом эфире на карте, именно там, где существует момент — и автоматически исчезает через 48 часов.', stat1Label:'Живых событий', stat2Label:'Городов', stat3Label:'Окно события', cta:'Открыть Live Pulse' },
    theExperience: { title:'Опыт', subtitle:'От Открытия к Созиданию' },
    noProfiles: { line1:'Без профилей.', line2:'Без подписчиков.', line3:'Без фильтров.', tagline:'Просто Presenz.' },
    places: { heading:'Места живые.', memory:'Места хранят память.', echo1:'Эхо музыки.', echo2:'Следы краски.', echo3:'Признаки людей, собирающихся, уходящих и возвращающихся.', closing:'Presenz позволяет местам говорить без рейтингов, отзывов и оценок.' },
    legal: { privacyTitle:'Конфиденциальность и EULA', eulaTab:'EULA', privacyTab:'Политика конфиденциальности', lastUpdated:'Последнее обновление: февраль 2026', legalLabel:'Правовая информация', questionsTitle:'Вопросы?', contactUs:'Связаться с нами', jumpTo:'Перейти к:', termsTitle:'Условия использования', termsIntro:'Используя PRESENZ, вы подтверждаете, что прочитали и приняли эти условия.' },
    footer: { home:'Главная', about:'О нас', downloadApp:'Скачать приложение', rights:'Presenz-IntusLab Inc. Все права защищены.', privacy:'Политика Конфиденциальности', terms:'Условия Использования' },
    about: { whoWeAre:'Кто Мы', heading:'О нас', subheading:'Новый вид платформы — созданной для присутствия, а не исполнения.', ourMission:'Наша Миссия', missionHeading1:'Presenz — это не', missionHeading2:'социальные сети.', missionDesc:'Presenz — это система для восприятия культуры в её моменты, в местах и атмосферах.', missionQuote:'"Оно существует, чтобы чувствовать то, что реально, пока оно ещё реально."', noPerformanceTitle:'Без исполнения', noPerformanceDesc:'Оно не просит людей исполнять или курировать свои моменты.', noAttentionTitle:'Без награды за внимание', noAttentionDesc:'Оно не вознаграждает внимание, лайки или петли вовлечённости.', noContentTitle:'Без контент-машины', noContentDesc:'Оно не превращает ваше присутствие в контент для распространения.', philosophy:'Философия', ourBelief:'Наши убеждения', beliefQuote1:'Культуре не нужно разрешение.', beliefLine1:'Она происходит на улицах. В звуках. В стенах.', beliefLine2:'В моментах, которые проходят до того, как кто-то их назовёт.', beliefTagline:'Культура — не контент. Это PRESENZ.', values:'Ценности', whatWeStandFor:'За что мы стоим', card1Title:'Без давления', card1Lines:['Без исполнения.','Без подписчиков.','Без давления.'], card2Title:'Без лент', card2Lines:['Без лент.','Без рейтингов.','Без петель валидации.'], card3Title:'Нечего выиграть', card3Lines:['Нечего выиграть.','Нечего сравнивать.'], ctaLine1a:'Ты не публикуешь.', ctaLine1b:'Ты замечаешь.', ctaLine2a:'Ты не скроллишь.', ctaLine2b:'Ты чувствуешь.', ctaLine3a:'Ты не исполняешь.', ctaLine3b:'Ты присутствуешь.', getApp:'Скачать' },
  },

  el: {
    nav: { home:'Αρχική', about:'Σχετικά', getApp:'Λήψη App', searchPlaceholder:'Αναζήτηση εκδηλώσεων, καλλιτεχνών, τόπων…', popularLabel:'Δημοφιλή', popularSearches:['Ζωντανή Μουσική','Εκθέσεις Τέχνης','Επιδείξεις Μόδας','Πολιτιστικές Εκδηλώσεις'], searchingFor:'Αναζήτηση για' },
    hero: { heading1:'Διαφορετικές Δονήσεις.', heading2:'Διαφορετικά Μέρη', tagline:'Μόνο PRESENZ.', description:'Ανακάλυψε τέχνη, μουσική, μόδα και πολιτισμό που συμβαίνουν ζωντανά κοντά σου.', cta:'Άφησε μια Presenz' },
    experience: { heading:'Ένας νέος τρόπος να βιώσεις τον πολιτισμό.', description:'Η Presenz συγκεντρώνει ζωντανή τέχνη, μουσική, μόδα, κινηματογράφο και αστική ενέργεια σε έναν ζωντανό χάρτη που φαίνεται μόνο ενώ συμβαίνει.', cardArtTag:'ΤΕΧΝΗ', cardArtTitle:'Σύγχρονη Έκθεση', cardArtVenue:'Fondation Beyeler', cardArtTime:'Τώρα – 6:00 μμ', cardMusicTag:'ΜΟΥΣΙΚΗ', cardMusicTitle:'Νυχτερινές Τζαζ Συνεδρίες', cardMusicVenue:'Blue Note Club', cardMusicTime:'8:00 μμ – Αργά', liveNow:'ΖΩΝΤΑΝΑ ΤΩΡΑ' },
    category: { heading:'Εξερεύνηση ανά κατηγορία', subheading:'Ανακάλυψε τι συμβαίνει τώρα στην πόλη', music:'Μουσική', food:'Φαγητό', night:'Νύχτα', cinema:'Κινηματογράφος' },
    iphone: { liveBadge:'Ζωντανά Τώρα', heading1:'Δες τι συμβαίνει.', heading2:'Εκεί που συμβαίνει.', description:'Κάθε παλμός εμφανίζεται ζωντανά στον χάρτη, ακριβώς εκεί που υπάρχει η στιγμή — και εξαφανίζεται αυτόματα μετά από 48 ώρες.', stat1Label:'Ζωντανά Events', stat2Label:'Πόλεις', stat3Label:'Παράθυρο', cta:'Άνοιγμα Live Pulse' },
    theExperience: { title:'Η Εμπειρία', subtitle:'Από την Ανακάλυψη στη Δημιουργία' },
    noProfiles: { line1:'Χωρίς προφίλ.', line2:'Χωρίς ακολούθους.', line3:'Χωρίς φίλτρα.', tagline:'Μόνο Presenz.' },
    places: { heading:'Οι τόποι είναι ζωντανοί.', memory:'Οι τόποι κρατούν μνήμη.', echo1:'Ήχος μουσικής.', echo2:'Ιχνη μπαγιάς.', echo3:'Σημεία ανθρώπων που μαζεύονται, φεύγουν και επιστρέφουν.', closing:'Presenz επιτρέπει στους τόπους να μιλούν χωρίς κατατάξεις, κριτικές ή κρίσεις.' },
    legal: { privacyTitle:'Απόρρητο & EULA', eulaTab:'EULA', privacyTab:'Πολιτική Απορρήτου', lastUpdated:'Τελευταία ενημέρωση: Φεβρουάριος 2026', legalLabel:'Νομικά', questionsTitle:'Ερωτήσεις;', contactUs:'Επικοινωνία', jumpTo:'Μεταβείτε σε:', termsTitle:'Όροι & Προϋποθέσεις', termsIntro:'Χρησιμοποιώντας το PRESENZ, επιβεβαιώνετε ότι έχετε διαβάσει και αποδεχτεί αυτούς τους όρους.' },
    footer: { home:'Αρχική', about:'Σχετικά', downloadApp:'Λήψη εφαρμογής', rights:'Presenz-IntusLab Inc. Όλα τα δικαιώματα διατηρούνται.', privacy:'Πολιτική Απορρήτου', terms:'Όροι Χρήσης' },
    about: { whoWeAre:'Ποιοι Είμαστε', heading:'Σχετικά', subheading:'Μια νέου είδους πλατφόρμα — φτιαγμένη για παρουσία, όχι επίδοση.', ourMission:'Η Αποστολή Μας', missionHeading1:'Η Presenz δεν είναι', missionHeading2:'κοινωνικά μέσα.', missionDesc:'Η Presenz είναι ένα σύστημα για την παρατήρηση του πολιτισμού όπως συμβαίνει σε μέρη, στιγμές και ατμόσφαιρες.', missionQuote:'"Υπάρχει για να νιώθει αυτό που είναι πραγματικό, όσο είναι ακόμα πραγματικό."', noPerformanceTitle:'Χωρίς επίδοση', noPerformanceDesc:'Δεν ζητά από τους ανθρώπους να εκτελούν ή να επιμελούνται τις στιγμές τους.', noAttentionTitle:'Χωρίς ανταμοιβή προσοχής', noAttentionDesc:'Δεν ανταμείβει προσοχή, likes ή βρόχους εμπλοκής.', noContentTitle:'Χωρίς μηχανή περιεχομένου', noContentDesc:'Δεν μετατρέπει την παρουσία σου σε κοινόχρηστο περιεχόμενο.', philosophy:'Φιλοσοφία', ourBelief:'Η πίστη μας', beliefQuote1:'Ο πολιτισμός δεν χρειάζεται άδεια.', beliefLine1:'Συμβαίνει σε δρόμους. Σε ήχους. Σε τοίχους.', beliefLine2:'Σε στιγμές που περνούν πριν κάποιος τις ονομάσει.', beliefTagline:'Ο πολιτισμός δεν είναι περιεχόμενο. Είναι PRESENZ.', values:'Αξίες', whatWeStandFor:'Για τι σταθήκαμε', card1Title:'Χωρίς πίεση', card1Lines:['Χωρίς επίδοση.','Χωρίς ακολούθους.','Χωρίς πίεση.'], card2Title:'Χωρίς feeds', card2Lines:['Χωρίς feeds.','Χωρίς κατατάξεις.','Χωρίς βρόχους επικύρωσης.'], card3Title:'Τίποτα να κερδίσεις', card3Lines:['Τίποτα να κερδίσεις.','Τίποτα να συγκρίνεις.'], ctaLine1a:'Δεν δημοσιεύεις.', ctaLine1b:'Παρατηρείς.', ctaLine2a:'Δεν κάνεις scroll.', ctaLine2b:'Νιώθεις.', ctaLine3a:'Δεν εκτελείς.', ctaLine3b:'Είσαι παρών.', getApp:'Λήψη App' },
  },

  pt: {
    nav: { home:'Início', about:'Sobre', getApp:'Obter App', searchPlaceholder:'Pesquisar eventos, artistas, lugares…', popularLabel:'Popular', popularSearches:['Música ao Vivo','Exposições de Arte','Desfiles de Moda','Eventos Culturais'], searchingFor:'Pesquisando por' },
    hero: { heading1:'Vibrações Diferentes.', heading2:'Lugares Diferentes', tagline:'Apenas PRESENZ.', description:'Descubra arte, música, moda e cultura acontecendo ao vivo perto de você.', cta:'Deixar uma Presenz' },
    experience: { heading:'Uma nova forma de experienciar a cultura.', description:'A Presenz reúne arte ao vivo, música, moda, cinema e energia urbana num mapa vivo visível apenas enquanto está acontecendo.', cardArtTag:'ARTE', cardArtTitle:'Exposição Contemporânea', cardArtVenue:'Fondation Beyeler', cardArtTime:'Agora – 18h00', cardMusicTag:'MÚSICA', cardMusicTitle:'Noite de Jazz Sessions', cardMusicVenue:'Blue Note Club', cardMusicTime:'20h00 – Tarde', liveNow:'AO VIVO' },
    category: { heading:'Explorar por categoria', subheading:'Descubra o que está acontecendo agora na cidade', music:'Música', food:'Comida', night:'Noite', cinema:'Cinema' },
    iphone: { liveBadge:'Ao Vivo Agora', heading1:'Veja o que está acontecendo.', heading2:'Onde está acontecendo.', description:'Cada pulso aparece ao vivo no mapa, exatamente onde o momento existe — e desaparece automaticamente após 48 horas.', stat1Label:'Eventos ao Vivo', stat2Label:'Cidades', stat3Label:'Janela de Evento', cta:'Abrir Live Pulse' },
    theExperience: { title:'A Experiência', subtitle:'Da Descoberta à Criação' },
    noProfiles: { line1:'Sem perfis.', line2:'Sem seguidores.', line3:'Sem filtros.', tagline:'Apenas Presenz.' },
    places: { heading:'Os lugares estão vivos.', memory:'Os lugares carregam memória.', echo1:'Ecos de música.', echo2:'Traços de tinta.', echo3:'Sinais de pessoas se reunindo, partindo e voltando.', closing:'A Presenz permite que os lugares falem sem ser classificados, revisados ou julgados.' },
    legal: { privacyTitle:'Privacidade & EULA', eulaTab:'EULA', privacyTab:'Política de Privacidade', lastUpdated:'Última atualização: Fevereiro de 2026', legalLabel:'Legal', questionsTitle:'Dúvidas?', contactUs:'Contate-nos', jumpTo:'Ir para:', termsTitle:'Termos e Condições', termsIntro:'Ao usar o PRESENZ, você confirma ter lido e concordado com estes termos.' },
    footer: { home:'Início', about:'Sobre', downloadApp:'Baixar app', rights:'Presenz-IntusLab Inc. Todos os direitos reservados.', privacy:'Política de Privacidade', terms:'Termos de Serviço' },
    about: { whoWeAre:'Quem Somos', heading:'Sobre', subheading:'Uma nova classe de plataforma — construída para a presença, não para a performance.', ourMission:'Nossa Missão', missionHeading1:'Presenz não é', missionHeading2:'mídia social.', missionDesc:'Presenz é um sistema para perceber a cultura enquanto ela acontece em lugares, momentos e atmosferas.', missionQuote:'"Existe para sentir o que é real, enquanto ainda é real."', noPerformanceTitle:'Sem performance', noPerformanceDesc:'Não pede às pessoas que performem ou curem seus momentos.', noAttentionTitle:'Sem recompensa de atenção', noAttentionDesc:'Não recompensa atenção, curtidas ou loops de engajamento.', noContentTitle:'Sem máquina de conteúdo', noContentDesc:'Não transforma sua presença em conteúdo compartilhável.', philosophy:'Filosofia', ourBelief:'Nossa crença', beliefQuote1:'A cultura não precisa de permissão.', beliefLine1:'Acontece em ruas. Em sons. Em paredes.', beliefLine2:'Em momentos que passam antes de alguém nomeá-los.', beliefTagline:'Cultura não é conteúdo. É PRESENZ.', values:'Valores', whatWeStandFor:'O que defendemos', card1Title:'Sem pressão', card1Lines:['Sem performance.','Sem seguidores.','Sem pressão.'], card2Title:'Sem feeds', card2Lines:['Sem feeds.','Sem rankings.','Sem loops de validação.'], card3Title:'Nada a ganhar', card3Lines:['Nada a ganhar.','Nada a comparar.'], ctaLine1a:'Você não publica.', ctaLine1b:'Você percebe.', ctaLine2a:'Você não rola.', ctaLine2b:'Você sente.', ctaLine3a:'Você não performa.', ctaLine3b:'Você está presente.', getApp:'Obter App' },
  },
}
